nginx:
  confPath: /usr/local/nginx/conf/nginx.conf
  logPath: /usr/local/nginx/logs/
  pidPath: /usr/local/nginx/logs/nginx.pid
auxiliary:
  confPath: /usr/local/nginx/conf/back/
  logPath: /usr/local/nginx/logs/oldlogs/
back:
  logDay: 15
  confNum: 30